[package]
name = "fanboi"
version = "0.1.0"
authors = ["Danielle Jenkins <git@d6e.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pid = "2.1.0"
clap = "2.33.3"
